#!/bin/bash

./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 1 >> out.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 1 1 >> out.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 5 >> out.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 1 5 >> out.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 10 >> out.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 1 10 >> out.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 15 >> out.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 1 15 >> out.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 20 >> out.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 1 20 >> out.out
