#!/bin/bash

./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 10 0 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 20 0 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 30 0 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 40 0 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 10 1 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 20 1 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 30 1 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 40 1 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 10 2 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 20 2 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 30 2 >> out1.out
./rm.sh
numactl --cpunodebind=1 --membind=1 ./src/test 0 40 2 >> out1.out
./rm.sh